### PR TITLE
Catch SocketTimeoutExceptions

### PR DESCRIPTION
**Pull request by Brycey92**

### CODE REVIEW

**Comment by Brycey92** [comment]
Hmm, it looks like the issue I'm having is not a bug, but a design decision. I'll close this for now and look further into it later.

**Comment by BrainStone** [comment]
What issue exactly were you trying to address?

**Comment by Brycey92** [comment]
Every so often, my console is spammed with timeout errors where Aura couldn't contact Ore or couldn't load a plugin's page on Ore.

I think though that when printing the exception's message, Aura is also printing its stack trace, which in this case (and probably most network exceptions) is unnecessary. Maybe the stack traces could be printed to debug output, and only the actual message like "Socket timed out" could be printed as a warning.

If you want me to, I can open an issue on the tracker to better organize this discussion.

**Comment by BrainStone** [comment]
I see. Your solution would provide at least an improvement. As only the first error gets printed in full.

But I do understand your concern and agree that there should be proper handling of timeouts.

**Pull request closed without merging**
